= Hawt.io
:toc:

This project creates a Docker image of link:https://hawt.io[hawt.io], a modular console for managing Java apps.

The image currently does not support any configuration options, it simply runs the module without security.

The Docker image of this app is available at https://hub.docker.com/r/incodehq/hawtio[Docker hub].



== Running Locally

To run the Docker image locally, use:

[source,bash]
----
export TAG=...

docker run -d -p8080:8080 incodehq/hawtio:$TAG
----

where `$TAG` is set to one of the images from the https://cloud.docker.com/u/incodehq/repository/docker/incodehq/hawtio/tags[tags page].

This exposes :

* the UI at port 8080 (that is, link:http://localhost:8080[]])


== Preconfigured Connections

Unfortunately hawt.io does _not_  currently allow connections to be pre-configured; see for example link:https://github.com/hawtio/hawtio/issues/1965[this] and link:https://github.com/hawtio/hawtio/issues/2268[this].
The only feature that is available is to invoke a URL which provides the connection parameters, as described link:https://github.com/hawtio/hawtio-java/issues/6#issuecomment-115295037[here].

That said, hawt.io _does_ remember previous connections in the browser local storage.
So, if you use the same browser to connect, then hawt.io will remember where you connected to previously.


== Further Reading

Additional info at:

* link:https://hawt.io[hawt.io] website


